DROP TABLE moneda CASCADE CONSTRAINTS;
DROP TABLE mercado CASCADE CONSTRAINTS;
DROP TABLE usuario CASCADE CONSTRAINTS;
DROP TABLE cartera CASCADE CONSTRAINTS;
DROP TABLE orden CASCADE CONSTRAINTS;
DROP TABLE transaccion CASCADE CONSTRAINTS;
DROP TABLE mer_mon CASCADE CONSTRAINTS;

DROP SEQUENCE seq_moneda;
DROP SEQUENCE seq_mercado;
DROP SEQUENCE seq_transaccion;
DROP SEQUENCE seq_dni;
DROP SEQUENCE seq_cartera;
DROP SEQUENCE seq_usuario;
DROP SEQUENCE seq_orden;


/*DROP TRIGGER tri_usuario;
DROP TRIGGER tri_cartera;
DROP TRIGGER tri_orden;
DROP TRIGGER tri_transaccion;
DROP TRIGGER tri_moneda;
DROP TRIGGER tri_moneda_after;
DROP TRIGGER tri_mercado;*/

